CREATE DATABASE defunciones_inegi;

use defunciones_inegi;

create table if not exists d_defunciones_generales (

	ent_regis INT,
	mun_regis INT,
	ent_resid INT,
	mun_resid INT,
	tloc_resid INT,
	loc_resid INT,
	ent_ocurr INT,
	mun_ocurr INT,
	tloc_ocurr INT,
	loc_ocurr INT,
	causa_def nvarchar(30),
	lista_mex nvarchar(30),
	sexo INT,
	edad INT,
	dia_ocurr INT,
	mes_ocurr INT,
	anio_ocur INT,
	dia_regis INT,
	mes_regis INT,
	anio_regis INT,
	dia_nacim INT,
	mes_nacim INT,
	anio_nacim INT,
	ocupacion INT,
	escolarida INT,
	edo_civil INT,
	presunto INT,
	ocurr_trab INT,
	lugar_ocur INT,
	necropsia INT,
	asist_medi INT,
	sitio_ocur INT,
	cond_cert INT,
	nacionalid INT,
	derechohab INT,
	embarazo INT,
	rel_emba INT,
	horas INT,
	minutos INT,
	capitulo INT,
	grupo INT,
	lista1 INT,
	gr_lismex nvarchar(10),
	vio_fami INT,
	area_ur INT,
	edad_agru INT,
	complicaro INT,
	dia_cert INT,
	mes_cert INT,
	anio_cert INT,
	maternas nvarchar(10),
	lengua INT,
	cond_act INT,
	par_agre INT,
	ent_ocules INT,
	mun_ocules INT,
	loc_ocules INT,
	razon_m INT,
	dis_re_oax INT
);